//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : pokerstudy
//  @ File Name : Card.cs
//  @ Date : 13.11.2013
//  @ Author : Tkachenko Roman
//
//


public class Card 
{
	private int suit;
	private int value;

	public Card()
    {
	}
    public Card(int suit, int value)
    {
    }
}
