//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : pokerstudy
//  @ File Name : Course.cs
//  @ Date : 13.11.2013
//  @ Author : Tkachenko Roman
//
//


public class Course 
{
	private string name;
	private ArrayList<Module> modules = new ArrayList<Module>();
	private string draft;

	public Course()
    {
	}
    public Course(string name, string draft)
    {
    }
	public void loadModule()
    {
	}
}
