//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : pokerstudy
//  @ File Name : Editor.cs
//  @ Date : 13.11.2013
//  @ Author : Tkachenko Roman
//
//


public class Editor 
{
	private Course course;

	private void loadCourse()
    {
	}
	private void saveCourse()
    {
	}
	private void exit()
    {
	}
}
