//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : pokerstudy
//  @ File Name : Menu.cs
//  @ Date : 13.11.2013
//  @ Author : Tkachenko Roman
//
//


public class Menu 
{
	private int userId;
	private string userName;
	private int userBank;
	private ArrayList<Course> courses = new ArrayList<Course>();

	private void authorize()
    {
	}
	private void callSettings()
    {
	}
	private void saveSettings()
    {
	}
	private void exitSettings()
    {
	}
	private void callEditor()
    {
	}
	private void play()
    {
	}
	private void loadCourse()
    {
	}
	private void changeUser()
    {
	}
}
