//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : pokerstudy
//  @ File Name : Module.cs
//  @ Date : 13.11.2013
//  @ Author : Tkachenko Roman
//
//


public class Module 
{
	private string name;
	private ArrayList<Task> tasks = new ArrayList<Task>();
	private string draft;

	public Module()
    {
	}
    public Module(string name, string draft)
    {
    }
	public void loadTask()
    {
	}
}
