//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : pokerstudy
//  @ File Name : Task.cs
//  @ Date : 13.11.2013
//  @ Author : Tkachenko Roman
//
//


public class Task 
{
	private string name;
	private string draft;
	private int rate;
	private string question;
	private ArrayList<Card> flop = new ArrayList<Card>();
	private Card[] hand = new Card[2];
	private string[] answers = new string[12];
	private int correctTurn;
	private int correctAnswer;

	public Task()
    {
	}
    public Task(string name, string draft, int rate, string question)
    {
	}
	public void makeTurn()
    {
	}
	public void makeAnswer()
    {
	}
}
